libname UKI "/var/blade/data2031/esiblade/zchunyou/UK_I/Data"; 

/*
proc contents data=UKI.All_consolidated;
run;
*/

proc sort data=UKI.All_consolidated;
by Label;
run;


proc glm data = UKI.All_consolidated;
by Label;
class AMID4;
model Sum_Revenue_Norm Sum_EGM_Norm = 
									AMID4 
									WA_Pct_On_Time_Demand
									WA_Pct_On_Time_Fulfillment
									WA_Avg_Days_To_Fill
									AE_Score
									AVG_CLengthWONRenewal2
									AVG_CLengthWONNew4
									AVG_CLengthWONAddOn4
									AVG_CLengthWONAddOn2
									count_oppDLNANew4
									count_oppWONRenewal2
									count_oppWONNew4
									count_oppWONAddOn4
									count_oppDLNARenewal2
									count_oppDLNAAddOn4
									count_oppWONAddOn2
									count_oppDLNAAddOn2
									WA_AddOn_Motion2_CloseRate
									WA_AddOn_Motion4_CloseRate
									WA_New_Motion4_CloseRate
									WA_Renewal_Motion2_CloseRate
									/*WA_AddOn_Motion2_WinRate
									WA_AddOn_Motion4_WinRate
									WA_New_Motion4_WinRate
									WA_Renewal_Motion2_WinRate*/
									CM_Successful
									CM_UnSuccessful_Changes_which_ar
									CM_UnSuccessful_Changes_which_do
									CM_UnSuccessful_changes_with_unk
									CM___Total_Changes
									CM___APPS
									CM___Cross_Functional___Multiple
									CM___DC_Facilities_Mgmt
									CM___EAO
									CM___ECSO
									CM___GSD
									CM___HPIT
									CM___ITO_OTHER
									CM___Mainframe
									CM___Networking_Services
									CM___Security_Services
									CM___Software_Services
									CM___Storage__Backup
									CM___UNIX_LINUX
									CM___Wintel
									CM___Workplace_Services
									CM___Emergency
									CM___NORMAL
									CM___Routine
									CM___Standard
									CM___NA
									RtOP_Count___ALPHA
									RtOP_Count___iRtOP
									RtOP_Count___RtOP
									RtOP_Count___vRtOP
									RtOP_CDT___ALPHA
									RtOP_CDT___iRtOP
									RtOP_CDT___RtOP
									RtOP_CDT___vRtOP
									RtOP_WDT___ALPHA
									RtOP_WDT___iRtOP
									RtOP_WDT___RtOP
									RtOP_WDT___vRtOP
									RtOP_ADT___ALPHA
									RtOP_ADT___iRtOP
									RtOP_ADT___RtOP
									RtOP_ADT___vRtOP
									RtOP___Significant
									RtOP___High
									RtOP___Medium
									RtOP___APPS_Org_
									RtOP___BPO_Org_
									RtOP___Business_Continuity_Recov
									RtOP___Client___Client_3rd_Party
									RtOP___Enterprise_Applications_O
									RtOP___Enterprise_Service_Mgmt__
									RtOP___HPIT
									RtOP___HPTS
									RtOP___Mainframe
									RtOP___Midrange___Database___Mid
									RtOP___Midrange___Legacy_Platfor
									RtOP___Midrange___UNIX_LINUX
									RtOP___Midrange___Wintel
									RtOP___Network
									RtOP___Other___Please_Specify
									RtOP___Production_Engineering
									RtOP___Program___Project_Managem
									RtOP___Security
									RtOP___Software_Services
									RtOP___Storage_Backup
									RtOP___Utility_Services_Cloud
									RtOP___WorkPlace_Services
									IM___Critical_CaseCount
									IM___High_CaseCount
									IM___Others_CaseCount
									IM___Critical_TTRMetNotCaseCount
									IM___High_TTRMetNotCaseCount
									IM___Others_TTRMetNotCaseCount
									IM___APPS
									IM___Cross_Functional___Multiple
									IM___EAO
									IM___ECSO
									IM___ESM
									IM___GSD
									IM___HPIT
									IM___ITO_OTHER
									IM___Mainframe
									IM___Networking_Services
									IM___Security_Services
									IM___Software_Services
									IM___Storage__Backup
									IM___UNIX_LINUX
									IM___Wintel
									IM___WorkPlace_Services
									ABS_TOTAL_COUNT
									ABS_UTILIZATION_RATE
									ABS_SINGLEACCOUNT_UTILIZATION_RA
									ABS_HIGH_COST_COUNTRY_COUNT
									ABS_HIGH_COST_COUNTRY_UTILIZATIO
									ABS_LOW_COST_COUNTRY_COUNT
									ABS_LOW_COST_COUNTRY_UTILIZATION
									ABS_GLOBAL_CENTER_COUNT
									ABS_GLOBAL_CENTER_UTILIZATION
									ABS_LOCAL_DELIVERY_COUNT
									ABS_LOCAL_DELIVERY_UTILIZATION
									ABS_REGIONAL_CENTER_COUNT
									ABS_REGIONAL_CENTER_UTILIZATION
									ABS_VOLUMETRIC_SERVICE_COUNT
									ABS_VOLUMETRIC_SERVICE_UTILIZATI
									ABS_Internal_COUNT
									ABS_INTERNAL_UTILIZATION
									ABS_VOLUMETRIC_DEMAND_COUNT
									ABS_VOLUMETRIC_DEMAND_UTILIZATIO
									ABS_ACCOUNT_FUNDED_FTE_COUNT
									ABS_ACCOUNT_FUNDED_FTE_UTILIZATI
									ABS_Overhead_COUNT
									ABS_Overhead_UTILIZATION
									ttir_avg_database_management
									ttir_avg_enterprise_applications
									ttir_avg_network_management
									ttir_avg_server_management
									ttir_avg_storage_management
									ttir_avg_customer_care
									ttir_avg_global_service_desk
									ttir_avg_managed_mainframe
									ttir_avg_managed_messaging
									ttir_avg_enterprise_cloud_servic
									ttir_avg_customer_specific
									ttr_avg_database_management
									ttr_avg_enterprise_applications
									ttr_avg_network_management
									ttr_avg_server_management
									ttr_avg_storage_management
									ttr_avg_customer_care
									ttr_avg_global_service_desk
									ttr_avg_managed_mainframe
									ttr_avg_managed_messaging
									ttr_avg_enterprise_cloud_service
									ttr_avg_customer_specific
									ct_inci_server_management
									ct_inci_enterprise_cloud_service
									ct_inci_database_management
									ct_inci_global_service_desk
									ct_inci_customer_care
									ct_inci_network_management
									ct_inci_enterprise_applications
									ct_inci_managed_messaging
									ct_inci_storage_management
									ct_inci_managed_mainframe
									ct_inci_customer_specific
									ctir_avg_customer_care
									ctir_avg_database_management
									ctir_avg_enterprise_applications
									ctir_avg_global_service_desk
									ctir_avg_managed_messaging
									ctir_avg_network_management
									ctir_avg_server_management
									ctir_avg_service_catalog
									ctir_avg_storage_management
									ct_inter_server_management
									ct_inter_global_service_desk
									ct_inter_service_catalog
									ct_inter_managed_messaging
									ct_inter_network_management
									ct_inter_enterprise_applications
									ct_inter_storage_management
									ct_inter_customer_care
									ct_inter_database_management/ solution ss3;
run;
